### ISSUE TITLE
MetricServerMiddlewareExtensions: Why re-enter with null url?

### ISSUE THREAD

**Issue by danielthompson** [prometheus-net/prometheus-net#130]
Hello,

Just curious, what is the purpose of rentering with a null `url` here? Would the method's behavior be any different if lines 14 and 15 were removed altogether (`url` isn't referenced after line 15)?

https://github.com/prometheus-net/prometheus-net/blob/986257f6ab8372cfd91f8fc12681394b3cda4cc2/Prometheus.AspNetCore/MetricServerMiddlewareExtensions.cs#L14-L15

**Comment by sandersaares** [comment]
The purpose is to map the metric server to the provided path (`/metrics/` by default). If lines 14 and 15 were removed, it would not be mapped to that path but the root path instead. After adding the path, we re-enter with null because now the root path is `/metrics/` and that's where we want to map the middleware to.
