### ISSUE TITLE
Add Content Encoding GZIP

### ISSUE THREAD

**Issue by condezero** [prometheus-net/prometheus-net#141]
It would be nice to have a way to accept Content-Encoding gzip or another compression type on KestrelMetricServer

**Comment by sandersaares** [comment]
After considering this feature request, I have decided to reject it from the backlog.

The reason is that there is already available the ASP.NET Core metric server, which is significantly more flexible in what it supports, allowing you to incorporate custom middleware (such as gzip) into the pipeline. Please use the ASP.NET Core server for such scenarios. 

The Kestrel server is kept at a minimal feature set in maintenance mode and is unlikely to receive significant updates in future versions.
