### ISSUE TITLE
Add Summary metric for request duration to HttpMetrics

### ISSUE THREAD

**Issue by pbelousov** [prometheus-net/prometheus-net#154]
Hi,

It looks it would be useful to add Summary metric in addition to Histogram metric for HTTP Request duration. 
Didn't you think about this? or Histogram metric is covering this case too?

Thank you!

**Comment by sandersaares** [comment]
There are two forms of the summary metric:

1. Count + sum, enabling basic averages to be counted.
1. Count + sum + quantiles, enabling quantiles to be determined.

I assume you are interested in the quantile data, as that is the most valuable part of the summary metric. The reason this is not currently included by default is that the quantiles are quite expensive to calculate (in terms of CPU and memory use) compared to other metrics. Capturing this data for requests seemed too wasteful if not explicitly requested by the user.

However, perhaps a possibility can be added to easily enable this metric on-demand and just let it default to off? I will consider and see if I can add such an enhancement in an easy to use manner.

**Comment by sandersaares** [comment]
I will close this for now but please feel free to leave a comment here or open up another issue if you feel there is still something missing.

**Comment by marcinjahn** [comment]
@sandersaares What would be the recommended way to add summaries to HTTP metrics in my app? I am not interested in the built-in histograms, because I am interested in the quantiles being calculated on the app's side.
Should I create custom middleware that publishes summary metrics, or would there be some other way to do that? I thought I could do that somehow via options in:

```
app.UseHttpMetrics(options =>
{
       // ???
}
```
but it seems there is now way to add new metrics this way.
