### ISSUE TITLE
No Support for AspNet 3 WebAPI? 

### ISSUE THREAD

**Issue by cdesewell** [prometheus-net/prometheus-net#168]
Hello

Just installed the asp package into an AspNet Core API project to find that my ApiController actions and labels aernt being picked up. Are API controllers not yet supported?

**Comment by futuralogic** [comment]
Hi,
I have added this to a .net core 3 web api project and I am able to get metrics. Can you clarify what you're not seeing, maybe a code sample?

In my case, I am using the built-in Http metrics, which are surfacing request duration (etc) for the API controller and action method.

I have used this library in other .net projects but just migrating some projects to .net core - so this is my first foray into .net core support.  I saw your question and thought I'd clarify, because I am seeing this work on .net core 3 during my research.

Example /metrics output for the request duration of one of the API actions:

`http_request_duration_seconds_bucket{code="200",method="GET",controller="SimpleApi",action="Get",le="0.512"} 4`

Additionally, when I create a metric (Gauge, example) in a controller I am also seeing it in /metrics, as expected.

Example:

In SimpleApiController.cs
```
// Defined in Controller class:
static readonly Gauge MyGauge = Metrics.CreateGauge( "my_gauge", "Some data" );

...

// Setting it in a controller action:
[HttpGet]
public async Task<ActionResult<List<SimpleData>>> Get() {
   MyGauge.Set( ( double )new Random().Next( 10000 ) );
}
```

Corresponding output in /metrics:
```
# HELP my_gauge Some data
# TYPE my_gauge gauge
my_gauge 1953
```

**Comment by sandersaares** [comment]
@cdesewell can you provide a sample project where you have ASP.NET Core 3 and prometheus-net not working? As @futuralogic posted above, it seems to work fine. If you have encountered a situation where it does not, I can investigate but I will need a way to reproduce your issue.

**Comment by sandersaares** [comment]
Closing due to timeout. If you have issues with ASP.NET Core 3, please open a new issue and post a full sample project that I can use to reproduce the issue.
