### ISSUE TITLE
ASP.NET Core 3.1 support

### ISSUE THREAD

**Issue by vlepeshev** [prometheus-net/prometheus-net#184]
Hello guys! 

I'm trying to use MapMetrics() in ASP.NET Core 3.1 project, but it seems like there is a limitation by NETCOREAPP3_0 directive in MetricServerMiddlewareExtensions.

Do you have any plans to support .NET Core 3.1?

**Comment by sandersaares** [comment]
This method is not yet published in a stable version - you need to upgrade to a preview package in order to use this method. The stable version of the package should be released within a few weeks.

If you do not want to upgrade to a preview package, you can simply use the ASP.NET Core 2 registration method (.UseMetricServer) - it still works with ASP.NET Core 3.1.

**Comment by vlepeshev** [comment]
Got it, thanks!
