### ISSUE TITLE
Accessing .UseMetricServer() endpoint hosted in IIS Express does not work from within the Prometheus container (but works from browser).

### ISSUE THREAD

**Issue by joacar** [prometheus-net/prometheus-net#200]
Hi,

I've set up Prometheus and Grafana in a docker container and use the `MetricServer` implementation ,that utilize `HttpListener`, on port 3030 and after allowing it using **netsh** Prometheus successfully start scraping my service running on my machine (docker host). 

If I remove that implementation and use Kestrel server created via `UseMetricServer()` the path`:<vs_port>/metrics` (VS random port, running IIS Express)  is no longer accessible from Prometheus. Can I implement a `MetricServerBackgroundService : IHostedService` to run the `MetricServer` implementation and not get the Kestrel-version set up?

Cause I can't make the networking stuff work for the Kestre based approach.

Thanks for a great package

**Comment by sandersaares** [comment]
I am unaware of the details of `IHostedService` implementation. `UseMetricServer()` is mainly intended for integration into apps that use the standard ASP.NET project templates. If you are doing something special, it might not be so well tested.

I can take a look (though I am no ASP.NET Core expert). Please post a full sample project (e.g. as a GitHub repo or attached zip file) that I can use to reproduce the problem you are experiencing.

**Comment by joacar** [comment]
The `IHostedService` is for running background workers (Kestrel it self implements this, if I'm not mistaken) outside of the request-pipeline. I've attached a sample application that enables events from `EventSource` implementation and reports the metrics using specific implementation. Currently the following metrics is reported

* Ongoing requests
* Failed requests
* Total requests

I'm about to implement metric for throughput (requests/second [time unit]), what is the best metric to use; Summary or Histogram? And should I report elapsed time in milliseconds or seconds? The naming of some metrics I've come across indicates that it's seconds.

Thanks

[WebApplication2.zip](https://github.com/prometheus-net/prometheus-net/files/4311473/WebApplication2.zip)

**Comment by sandersaares** [comment]
After re-reading your description, I think I see what the problem is. I will try to re-state the issue in different terms:

* Accessing `.UseMetricServer()` endpoint hosted in IIS Express does not work from within the Prometheus container (but works from browser).
* Accessing `HttpListener` endpoint works always.

Is this right? In that case, I believe this is by design - the default IIS Express configuration only allows connections from the same machine. The Prometheus container will typically run in a separate virtual machine or at the very least have a dedicated network adapter that acts in network terms as a separate machine.

There are some blog posts about how to work around this but I cannot say for sure how reliable they are.

The easiest solution might be to not use IIS Express but just to run the executable as a stand-alone Kestrel/Aspnetcore host. Alternatively, if you need IIS Express, you can try some of the workarounds. Finally, using full IIS might also be an option.

**Comment by joacar** [comment]
@sandersaares You're right and for local development I just use Kestrel instead. Thanks
