### ISSUE TITLE
export httpclient metrics

### ISSUE THREAD

**Issue by AChehre** [prometheus-net/prometheus-net#229]
[Here](https://github.com/AChehre/prometheus-net/tree/httpclient) is my fork of this project and wrote the HttpClient metrics exporter.
it's not final so I appreciate for any idea or review.
I can separate this project or create a new pull request if we are in the same way.
I'm working on DiagnosticListener and this kind of stuff to complete the exporter (for legacy projects)
tnx

**Comment by sandersaares** [comment]
Oh, this looks quite nice!

I am not familiar with HttpClient versioning - what dependencies does this feature have? Is it compatible with .NET Standard 2.0 or does it require something newer?

I notice that the HTTP request path is a label. This can lead to a large number of metrics, as the values can be rather unbounded. That is, if my software is downloading images, I would rather see a `http_client{type = "image_download"}` metric, instead of individual metrics for different images (`http_client{path = "/image1.jpg"}`, `http_client{path = "/image2.jpg"}`). What would you suggest as the optimal mechanism to achieve this "categorized" grouping of HTTP client metrics, instead of URL based (if at all possible)?

**Comment by AChehre** [comment]
Thanks, I tried to write like your great Asp.Net middleware project.

> I am not familiar with HttpClient versioning - what dependencies does this feature have? Is it compatible with .NET Standard 2.0 or does it require something newer?

It's compatible with .NET Standard 2.0 & in this project I used .Net Core 3.1 for the extension(HttpClientFactory).
for my company, I wrote a metric exporter for HttpClient and an Asp.Net Core extension in another project for use with HTTP client builder.

> I notice that the HTTP request path is a label. This can lead to a large number of metrics, as the values can be rather unbounded. That is, if my software is downloading images, I would rather see a http_client{type = "image_download"} metric, instead of individual metrics for different images (http_client{path = "/image1.jpg"}, http_client{path = "/image2.jpg"}). What would you suggest as the optimal mechanism to achieve this "categorized" grouping of HTTP client metrics, instead of URL based (if at all possible)?

Yes, you are right, that was because I'm working with a few URLs and services.
We can change it to the optional parameters(with name routes) as you wrote in Asp.Net middleware.

Let me create another repo in my Github and write some test for them.

**Comment by sandersaares** [comment]
I have merged your PR - many thanks! Let's continue discussion on the HttpClient identification topic under #257
