### ISSUE TITLE
How to aggregate min/max values of a gauge metric?

### ISSUE THREAD

**Issue by mhoyer** [prometheus-net/prometheus-net#240]
The given four metric types (`Counter`, `Gauge`, `Summary` and `Histogram`) are fine and help us already in getting insights of our services. But I often hear from developers around me that it's still too fuzzy in some cases, because the collect cycle does only provide aggregated values - which makes total sense. 

A concrete example of what we are missing: when measuring request durations it would be interesting to know the maximum duration for each collector cycle (within the 10s loop). `Summary` and `Histogram` are already doing implicit aggregations (`_count`, `_sum`), but what's missing for us are `_min` and `_max` aggregations for gauge like measurements.

I tried to create a custom metric type `MinMaxGauge` by implementing `Collector<T>`, but that's not possible due to restrictions by access modifiers (for instance `MetricType` is an internal `enum`). Inheritance of `Gauge` is also not working as it is a `sealed` class.

Building something around the given API, which wraps the `Metrics.CreateGauge()` and `.AddBeforeCollectCallback()` (to reset the aggregated values) also feels not right and bloated.

Maybe I am missing some logical restriction. Are there any other approaches to achieve our goals?

**Comment by sandersaares** [comment]
The API is quite intentionally restricted to the 4 metric primitives, as this follows standard Prometheus architecture across different languages and platforms.

One part of the Prometheus architecture is also that the metric recording should not depend on the metric collection. It is perfectly valid scenario to collect metrics from a single app using more than 1 Prometheus server. Having things "reset" because of a collection would lead to undesirable behavior in such scenarios.

The builtin metrics therefore do not have such behavior. As you noted, you could synthesize this using `Metrics.CreateGauge()` and `.AddBeforeCollectCallback()` which is likely the best approach if you want to achieve this.
