### ISSUE TITLE
Question: Having multiple exporters in one application.

### ISSUE THREAD

**Issue by Johnson-Hsu** [prometheus-net/prometheus-net#286]
Hi,

I designed an application which reads information from 30 industrial devices and each of them has a set of parameters (10-50 per device) to read. Now I want to export these data to Prometheus but not sure what would be the best way to do. My current idea is to export parameters of each device from a different port (one exporter per device) instead of merging them together.

Is it possible to do this? Or what would be a better way to achieve this?

If there is any wrong understanding about Prometheus, please correct me since I'm just starting. Thanks.

**Comment by Mario-Hofstaetter** [comment]
> My current idea is to export parameters of each device from a different port (one exporter per device)

This seems very wrong to me and painful to maintain (if count of devices changes to 35, you need 5 additional ports? Firewall rules, Prometheus Config Update, ...)

**In my opionion just have all metrics in one exporter, the metrics should expose one ore more `Labels` identifying the industrial device.** This is how other exporters do it (e.g. SQL Exporters querying multiple SQL databases)

Since you are new to prometheus take at least a look at these resources:
- <https://prometheus.io/docs/practices/naming/>
- <https://prometheus.io/docs/concepts/jobs_instances/>
- <https://prometheus.io/docs/practices/instrumentation/>
- And many more 😄

**Comment by sandersaares** [comment]
The above answer seems right on the money, so I will close this. In general, questions of metrics design are better aimed at the prometheus-users mailing list, as this GitHub repo is for issues specifically related to usage of the prometheus-net library.
