### ISSUE TITLE
Additional metrics after moving to dotnet 8 & promtheus-net 8 & metrics appear to be deleted by default

### ISSUE THREAD

**Issue by andy-g** [prometheus-net/prometheus-net#462]
After upgrading `prometheus-net` to version 8, I noticed a substantial increase of metrics in the metrics endpoint, it appears that the following metrics have been automatically added.
```
microsoft_aspnetcore_routing_aspnetcore_routing_match_attempts
system_net_nameresolution_dns_lookup_duration
system_net_http_http_client_connection_duration
system_net_http_http_client_request_time_in_queue
microsoft_aspnetcore_hosting_http_server_request_duration
microsoft_aspnetcore_server_kestrel_kestrel_connection_duration
system_net_http_http_client_request_duration
```

Some of these appear to be related to http clients within the application, but I do not have `services.UseHttpClientMetrics();` enabled. 

I was wondering if there is any easy way to revert back to the same metrics as v7 had. I did notice the `Metrics.SuppressDefaultMetrics();` option which should satisfy my needs as it seems to keep the `http_request_duration_seconds` metric which was included in the v7 metrics, the only none custom metric that I require (probably because I've included `app.UseHttpMetrics();` after specifying `Metrics.SuppressDefaultMetrics();`). Otel allows specific meters to be added (https://learn.microsoft.com/en-us/dotnet/core/diagnostics/observability-with-otel#5-configure-opentelemetry-with-the-correct-providers), and I was wondering if `prometheus-net` offers something similar to choose specifically which metrics to include.

In addition to this, looking at prometheus metrics, I was surprised to see that the sample count from scraping the metrics endpoint was going up and down (I expected it to only go up unless the process was restarted). I did notice the new `WithManagedLifetime` functionality (https://github.com/prometheus-net/prometheus-net#deleting-metrics), which I assume is the reason for it, but I didn't enable this. Is this enabled by default? Surely if metrics are removed between scrapes there's a chance that some incremented values will be lost? If this is on by default, can it be turned off.

**Comment by sandersaares** [comment]
By default, recent prometheus-net versions will [export metrics published via the .NET Meters API](https://github.com/prometheus-net/prometheus-net#net-meters-integration). If you do not want these metrics to be exported, you can indeed use `Metrics.SuppressDefaultMetrics()`. This also has an overload that takes a `SuppressDefaultMetricOptions` for more fine-grained control.

Alternatively, if you wish to keep the .NET Meters API metrics, you can fine-tune their export (and filter out instruments you do not want) by calling `Metrics.ConfigureMeterAdapter()`.

> Is this enabled by default? Surely if metrics are removed between scrapes there's a chance that some incremented values will be lost? If this is on by default, can it be turned off.

Yes, metrics exposed via the .NET Meters API by default expire after 5 minutes since there is no functionality in the .NET Meters API to say that a timeseries has gone away, which risks garbage building up in memory (as many client apps create unique metrics per request/session or similar business objects, which would stick around forever without this expiration). This only affects the .NET Meters API adapter.

You can configure this timeout via `Metrics.ConfigureMeterAdapter()`. See [MeterAdapterOptions](https://github.com/prometheus-net/prometheus-net/blob/master/Prometheus/MeterAdapterOptions.cs) for a list of all the possible configuration options.

**Comment by andy-g** [comment]
@sandersaares thanks so much for the detailed response, that really helps point me in the right direction, I'm sure I'll be able to configure the metrics I'm needing based on what you've outlined.

Thanks again.
