### ISSUE TITLE
Metric pusher fails with .net standard package

### ISSUE THREAD

**Issue by dotnetdude** [prometheus-net/prometheus-net#75]
I have used the sample test code given for metric pusher and used the .net standard version of the package and it failed with the following message when i try to access metrics url. 

```
An error has occurred:

expected counter in metric process_cpu_seconds_total label:<name:"instance" value:"App_Name" > label:<name:"job" value:"App_Domain" > gauge:<value:0.296875 > 

```

it works fine if i change the package to full framework version

**Comment by sandersaares** [comment]
Thank you for the report! I think I understand what is happening here:

1. prometheus-net by default includes collectors for some basic. NET metrics (like its own CPU usage and .NET memory statistics)
1. The metric pusher sends this to the Pushgateway.
1. Pushgateway overwrites some of this data with metrics about its own process stats, merging the two data sets.
1. Because some of the metric types are different, Pushgateway experiences an error when it tries to use the merged metrics.

It is a bit unexpected that this hidden dependency exists but it seems to be unavoidable.

To fix this, prometheus-net will be adjusted so that any metric types that are also present in Pushgateway are compatible with what prometheus-net uses.

**Comment by sandersaares** [comment]
A new preview package is now published, carrying the version string `2.0.0-pre-003077-0447c86`. Please let me know if this fixes the issue for you.

**Comment by dotnetdude** [comment]
Thanks. Just tested with the version 2.0.0-pre-003077-0447c86 and it solved this issue. I can access the metrics URL without any errors.

**Comment by dotnetdude** [comment]
is there any flag or any code to stop collecting default metrics?

**Comment by sandersaares** [comment]
Glad to hear your problem got resolved. I will mark this issue as closed then. Feel free to reopen if it feels that there is still something wrong with this scenario.

To remove the default .NET process metrics, you can call `DefaultCollectorRegistry.Instance.Clear()` on app startup (before registering your own metrics).

Alternatively, you can create a custom instance of the registry (`new DefaultCollectorRegistry()`) and use it to register your metrics (`Metrics.WithCustomRegistry(...).CreateXYZ()`) and provide it to MetricPusher. However, this is likely more work if you are not already using a custom registry.

**Comment by dotnetdude** [comment]
Thanks. I am currently leaving the default metrics as they may be useful in future. If it is not useful in long run, I will use the DefaultCollectorRegistry.Instance.Clear() method to remove those metrics.
