### ISSUE TITLE
Built-in HTTP server metrics middleware

### ISSUE THREAD

**Issue by ozkar99** [prometheus-net/prometheus-net#83]
any plans on adding http_server metrics on the middleware?

talking about duration of requests or total count of requests, like the ruby or go client does.

**Comment by sandersaares** [comment]
There are currently no such plans. Would you be interested in contributing such a feature? If so, we could discuss details about how and what to implement.

**Comment by ozkar99** [comment]
Definetly,

i've noticed that:  https://github.com/PrometheusClientNet/Prometheus.Client.HttpRequestDurations
already implements the functionality, but since this is THE dotnet ofically unoficial (since its linked on the prometheus clients page) 

I could start by trying to port that functionality.

**Comment by sandersaares** [comment]
Taking reference from the [official Go implementation](https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/instrument_server.go) would be ideal, as it seems to exemplify a good number of Prometheus best practices.

With any web request instrumentation, it would be important to avoid an explosion in the number of exported metrics simply because many different URLs are accessed by users. The Go implementation only applies Code and Method labels by default, which I think is a good choice and helps keep this under control.

It would be nice to have an implementation that is natively focused on ASP.NET Core concepts like controllers and actions rather than path-string parsing, as in the linked implementation. Perhaps the implementation could auto-detect some "controller" and "action" labels instead of focusing on paths? I see there is some relevant info in a [ControllerActionDescriptor class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllers.controlleractiondescriptor?view=aspnetcore-2.0), though I do not know from where the middleware would get an appropriate instance of this class.

Naturally, not every HTTP request goes to a controller/action. Such requests would have these labels with empty values.

Go implementation exposes the following metrics:

* requests currently being processed
* duration (histogram/summary)
* request count
* time until response headers are written
* request size (histogram/summary)
* response size (histogram/summary)

That is a good set of metrics to target, in general. If I read the code right, it is up to the user of the code to decide if they want a histogram or summary. That's rather nice in terms of flexibility, though I suspect prometheus-net does not currently support it (but it might be easy to add this abstraction).

An implementation along these lines would be very welcome. I would be happy to merge one with only partial metrics from the Go list (whatever is easiest to implement). The crucial point would be how to arrange the integration in a way that series explosion due to many different labels would be avoided.

I would be satisfied with an initial implementation that simply ignores paths altogether any just exposes controller/action name. Users of the library would likely benefit also from additional extensibility to expose more labels in some conditions but that could be added in a later version.

Apologies for delayed reply! I hope this feedback provides some useful input for this effort.

**Comment by cmannix** [comment]
Hi all - I'm interested in taking this on over the next week or so, based on your suggestions @sandersaares - would that be OK with both of you?

**Comment by erbrecht** [comment]
This library is great, and these added http metrics are exactly what I was looking for. I tried using App Metrics and I just couldn't get it to work. This is very simple and easy to set up. I built the library from @cmannix's fork, and it's looking really good so far, exactly what I've been needing. Just wanted to say thanks to everyone who put in time and effort on this.

**Comment by sandersaares** [comment]
#112 is merged to master, should be available as preview nuget package within a few hours once I do preliminary validation and adjustments.

The following is now implemented:

* request count
* request duration
* currently executing request count

**Comment by sandersaares** [comment]
3.0.0 with the above is now published.
