### ISSUE TITLE
Why introducing breaking changes but not support both NetStandard and NET452

### ISSUE THREAD

**Issue by anisimovyuriy** [prometheus-net/prometheus-net#87]
Thanks a lot for such a great prometheus client!

I have one issue though that I have one library that supports both NET452 and NetStandard 2.0. Would you consider to include NET452 binaries and NetStandard 2.0 in one nuget package same as done in Prometheus.Client?

Thanks!

**Comment by sandersaares** [comment]
I am afraid this is quite intentional - it is important to keep the library easy to maintain, as there is very little developer time available to allocate on it and targeting multiple .NET variants would be an undesirable complication due to both increasing the test surface and bringing with it compatibility constraints.

If you wish to target an old version of .NET Framework, you can always just use a 1.x version of prometheus-net until you are able to upgrade your target framework version.
