### ISSUE TITLE
Add prefix for sample metrics

### ISSUE THREAD

**Issue by alvillain** [prometheus-net/prometheus-net#91]
Hi,

The documentation says that the sample metrics can be removed by calling **DefaultCollectorRegistry.Instance.Clear()**. Is there way to add a prefix for those metrics?
E.g. my app is called "MyApp", I would like to have one of those metrics called like: _myapp_process_windows_processid_.

Thanks.

**Comment by virth** [comment]
No there's not. It would actually be pretty easy to implement but it's just not the way metrics names should be used. That's what labels are for. You should add a label 'application:myApp'. Maybe have a look at the [prometheus best practices](https://prometheus.io/docs/practices/naming/)

I suggest this issue should therefore be closed.

**Comment by sandersaares** [comment]
I agree with the above. You should use labels for such purposes. Also, for easier managability, prefer adding labels from the Prometheus side (labeling based on "what am I collecting from") instead of from the producer side ("what am I reporting for").

Ultimately, of course, you can just replace the sample metrics with your own if you really do want to achieve this. The samples are mostly in the library just to avoid "I installed but get no data" misunderstandings - just to have something show up. Not really meant to be very useful in production scenarios to any large extent.

I close this issue since I foresee no changes to prometheus-net coming from this. If you think there is still room for action, please feel free to leave a comment or open a new issue.
