### ISSUE TITLE
Prometheus issue with Framework 4.6.1

### ISSUE THREAD

**Issue by satishviswanathan** [prometheus-net/prometheus-net#99]
Target Framework: 4.6.1

I have the prometheus-net package installed in my web api project and now the message handler are throwing with the following exception during the application start up.

Exception Details: System.MissingMethodException: Method not found: 'System.Collections.ObjectModel.Collection`1<System.Net.Http.DelegatingHandler> System.Web.Http.HttpConfiguration.get_MessageHandlers()'.

Any help in the issue is highly appreciated.

**Comment by sandersaares** [comment]
Stack Overflow hints that this may be due to missing binding redirects for System.Net.Http: https://stackoverflow.com/questions/47183899/error-when-referencing-net-standard-2-0-library-from-asp-net-4-7-project

Recent versions of Visual Studio auto-generate binding redirects. Older versions did not do so. Make sure that your Visual Studio is up to date and that all System NuGet packages are updated.

If the above does not help, please provide a sample program that reproduces the issue, so I could try investigate further.

**Comment by satishviswanathan** [comment]
Thank you, that worked !
